### ISSUE TITLE
Editing features does not support polygons

### ISSUE THREAD

**Issue by XuBaocai** [desertwolf7/NumericalDigitize#3]
Editing features does not support polygons. When you select a polygon, an error occurs when executing Python code. If the polygon is a saved ShapeFile file, this error will not occur. Please repair it when you have time. Thank you.

**Comment by desertwolf7** [comment]
What is the version of qgis? What is the type of layer? Can you send text of Python error?

**Comment by XuBaocai** [comment]
The QGIS I use is 3.16.5, and the layer type is polygon. Can you help me to have a look if you have time? thank you!!!

`2021-04-05T07:46:57     WARNING    Traceback (most recent call last):
              File "C:/Users/XINXI/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\numericalDigitize\numericalDigitize.py", line 264, in EditFeature
              self.__dlgEdit.setValues(coords)
              File "C:/Users/XINXI/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\numericalDigitize\addFeatureGUI.py", line 273, in setValues
              model.insertRows(0, len(self.coords_matrix[0][1]) + 1)
             IndexError: list index out of range`
`2021-04-05T07:46:57     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.`

**Comment by XuBaocai** [comment]
[Polygon.zip](https://github.com/desertwolf7/NumericalDigitize/files/6255704/Polygon.zip)

**Comment by XuBaocai** [comment]
![2021-04-05_074823](https://user-images.githubusercontent.com/66826351/113525446-92ee3200-95e7-11eb-8fc8-6153325d62a2.jpg)

**Comment by XuBaocai** [comment]
It's normal now, thank you very much.
